#import "theme/modules/CategoryItem/CategoryItemFragment.gql"

fragment CategoryItemFragment on Category {
  name
  layer(params: $params) {
    categories {
      ...CategoryItemFragment
    }
  }
}
