type Query {
  "Fetch all categories"
  categories: [Category]
  "Fetch a category by code"
  category(code: String!): Category
}

type Category {
  "The category's ID"
  code: String!
  "The category's name"
  name: String
  "The category's URL"
  url: String!
}
