type Query {
  "Fetch all products"
  products: [Product]
  "Fetch all categories"
  categories: [Category]
  "Get a category by code"
  category(code: String!): Category
}

"A product"
type Product {
  "The product's SKU"
  sku: String
  "The product's name"
  name: String
  "The product's description"
  description: String
}

"A category"
type Category {
  "The category's url"
  url: String
  "The category's name"
  name: String
  "The category's products"
  children: [Product]
}
