type Query {
  "Fetch all products"
  products: [Product]
  "Fetch one product by its SKU"
  product(sku: String!): Product
  "Products contained in a category"
  productsByCategory(categoryCode: String!): [Product]
}

"A product"
type Product {
  "The product's SKU"
  sku: String
  "The product's name"
  name: String
  "The product's description"
  description: String
  "The product's image URL"
  imageUrl: String
}
